### ISSUE TITLE
[Q] how to setup the Secrets.toml streanlite 

### ISSUE THREAD

**Issue by deep-matter** [dfavenfre/LLMRoboFund#1]
i have got a problem with Setup the Toml file some argments i don't know what are means 

```python 
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/workspaces/LLMRoboFund/Application/app.py", line 2, in <module>
    from agent import run_robofund_agent
  File "/workspaces/LLMRoboFund/Application/agent.py", line 14, in <module>
    sql_tool = query_from_sql()
               ^^^^^^^^^^^^^^^^
  File "/workspaces/LLMRoboFund/Application/tools.py", line 28, in query_from_sql
    with open(st.secrets.SQL_PROMPT, "r") as file:
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/streamlit/runtime/secrets.py", line 296, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.secrets has no attribute "SQL_PROMPT". Did you forget to add it to secrets.toml or the app settings on Streamlit Cloud? More info: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management
```

**Comment by dfavenfre** [comment]
@deep-matter Hi, I believe you are trying to run up the application on your local machine, however, the **application** directory has been prepared for deploying it on Streamlit cloud. If that's not the case for you, and I suggest you to replace `st.secrets` with `os.environ.get("your_api_keys_or_paths"),`. 
 

**SQL_PROMPT** is I believe the URI path of the Sqlite db, it's been ages since I finished this project and cannot recall what it was for atm.
